refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{l}] {t} - {m}{n}"
  
  filelog:
    kind: file
    path: "log/tinydns.log"

root:
  level: error
  appenders:
    - stdout
    - filelog

loggers:
  tinydns:
    level: trace
