refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{l}] {M} - {m}{n}"
  
  dns_requests:
    kind: file
    path: "log/dns_requests.log"

root:
  level: trace
  appenders:
    - stdout

loggers:
  tinydns::server::handle_packet:
    level: info
    appenders:
      - dns_requests